### ISSUE TITLE
terminated with exit code: 1. - please HELP!

### ISSUE THREAD

**Issue by murraa** [viktak/Light-Panels#3]
> Executing task: C:\Users\murra\.platformio\penv\Scripts\platformio.exe run --environment esp12e <

Warning! Ignore unknown configuration option `major_build_number` in section [env:esp12e]
Processing esp12e (platform: espressif8266; framework: arduino; board: esp12e)
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option

warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=False to SConscript calls.
Missing SConscript 'D:\ActoSenso\Nodes\_common\tools\versioning\preIncrementBuildNumber.py'
File "C:\Users\murra\.platformio\penv\lib\site-packages\platformio\builder\main.py", line 179, in <module>
CONFIGURATION: https://docs.platformio.org/page/boards/espressif8266/esp12e.html
PLATFORM: Espressif 8266 (3.2.0) > Espressif ESP8266 ESP-12E
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES:
 - framework-arduinoespressif8266 3.30002.0 (3.0.2)
 - tool-esptool 1.413.0 (4.13)
 - tool-esptoolpy 1.30000.201119 (3.0.0)
 - toolchain-xtensa 2.100300.210717 (10.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 42 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <ArduinoJson> 6.19.4
|-- <PubSubClient> 2.8.0
|-- <Time> 1.6.1
|-- <Ticker> 4.4.0
|-- <Timezone> 1.2.4
|   |-- <Time> 1.6.1
|-- <NeoPixelBus> 2.6.9
|   |-- <SPI> 1.0
|   |-- <I2S> 1.0
|-- <Button2> 2.0.0
|-- <ESP8266WiFi> 1.0
|-- <ArduinoOTA> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ESP8266mDNS> 1.2
|   |   |-- <ESP8266WiFi> 1.0
|-- <EEPROM> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WebServer> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <LittleFS> 0.1.0
Building in release mode
Compiling .pio\build\esp12e\src\main.cpp.o
Generating LD script .pio\build\esp12e\ld\local.eagle.app.v6.common.ld
Compiling .pio\build\esp12e\lib033\PubSubClient\PubSubClient.cpp.o
Compiling .pio\build\esp12e\libd9f\Time\DateStrings.cpp.o
Compiling .pio\build\esp12e\libd9f\Time\Time.cpp.o
Compiling .pio\build\esp12e\lib6fe\Ticker\Ticker.cpp.o
Compiling .pio\build\esp12e\lib55d\Timezone\Timezone.cpp.o
In file included from src\main.cpp:6:
include/includes.h:6:10: fatal error: ../../../ActoSenso/Nodes/_common/debug.h: No such file or directory
    6 | #include "../../../ActoSenso/Nodes/_common/debug.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Compiling .pio\build\esp12e\lib703\SPI\SPI.cpp.o
Compiling .pio\build\esp12e\lib157\I2S\I2S.cpp.o
*** [.pio\build\esp12e\src\main.cpp.o] Error 1
.pio\libdeps\esp12e\PubSubClient\src\PubSubClient.cpp: In member function 'boolean PubSubClient::publish_P(const char*, const uint8_t*, unsigned int, boolean)':
.pio\libdeps\esp12e\PubSubClient\src\PubSubClient.cpp:523:16: warning: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Wsign-compare]
  523 |     return (rc == expectedLength);
      |             ~~~^~~~~~~~~~~~~~~~~
=================================================================================== [FAILED] Took 4.15 seconds ===================================================================================
The terminal process "C:\Users\murra\.platformio\penv\Scripts\platformio.exe 'run', '--environment', 'esp12e'" terminated with exit code: 1.

Terminal will be reused by tasks, press any key to close it.

**Comment by viktak** [comment]
The warning about `major_build_number` can be ignored - it is a custom variable I use in a script, and it is not necessary for the compilation. You can use instead the following defines:
```
  #define BUILD_NUMBER "854"
  #define FIRMWARE_VERSION "v1.1.854 - 2022-04-11 12:24:07.400299"
  #define FIRMWARE_VERSION_SHORT "v1.1.854"
```
Or something similar. It doesn't really matter what they are.

As for the error in `debug.h` - You are probably mixing up something, as there is no such file in the project. There may have been - I can't remember. Please update your project from the original.
